# Generated by Django 5.1.2 on 2024-12-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='educationtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('sslc_school', models.CharField(max_length=255)),
                ('sslc_year', models.IntegerField()),
                ('sslc_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plus_two_school', models.CharField(max_length=255)),
                ('plus_two_year', models.IntegerField()),
                ('plus_two_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('degree_college', models.CharField(max_length=255)),
                ('degree_course', models.CharField(max_length=255)),
                ('degree_year', models.IntegerField()),
                ('degree_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Type', models.CharField(max_length=150)),
            ],
        ),
    ]
