# Generated by Django 5.1.2 on 2024-12-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_educationtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicaltable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('blood_group', models.CharField(max_length=3)),
                ('gender', models.CharField(help_text='Specify gender (e.g., Male, Female, Other)', max_length=10)),
                ('allergies', models.TextField(blank=True, help_text='List any allergies')),
                ('emergency_contact', models.CharField(help_text='Name and phone number', max_length=100)),
                ('medications', models.TextField(blank=True, help_text='List current medications')),
            ],
        ),
    ]
