# Generated by Django 5.1.2 on 2024-12-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_medicaltable'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Account Holder Name')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=20, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(max_length=15, verbose_name='IFSC Code')),
                ('account_type', models.CharField(max_length=50, verbose_name='Account Type')),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Annual Income')),
            ],
        ),
    ]
