# Generated by Django 5.1.2 on 2024-12-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_accounttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='culturaltable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('residence', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=1000)),
                ('ethnicity', models.CharField(max_length=1000)),
                ('practices', models.CharField(max_length=1000)),
                ('festivals', models.CharField(max_length=1000)),
                ('clothing', models.CharField(max_length=1000)),
                ('additional', models.CharField(max_length=1000)),
            ],
        ),
    ]
