# Generated by Django 5.1.2 on 2024-12-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_culturaltable'),
    ]

    operations = [
        migrations.CreateModel(
            name='goaltable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('shortTermGoals', models.CharField(max_length=1000)),
                ('longTermGoals', models.CharField(max_length=1000)),
                ('dreamDestinations', models.CharField(max_length=1000)),
                ('bucketListItems', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='culturaltable',
        ),
    ]
